myPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ProjectListView.as_view(), name='index'),
    path('portfolio/', include("portfolio_app.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio_app/urls.py
from django.urls import path
from portfolio_app import views
app_name = 'portfolio_app'


urlpatterns = [
    path('contact/', views.contact, name="contact"),
    path('my-projects/<slug:slug>', views.ProjectDetailView.as_view(), name='projects'),
    path('update/<slug:slug>', views.ProjectUpdateView.as_view(), name='update'),
    path('new-project/', views.ProjectCreateView.as_view(), name='create'),
]

portfolio_app/models.py
from django.db import models
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
# Create your models here.
from django.utils import timezone

WEB_HOST_TYPE = [
    ('Cloud', 'Cloud'),
    ('VPS', 'VPS'),
    ('Shared Hosting', 'Shared Hosting'),
]

class Project(models.Model):
    name = models.CharField(max_length=250)
    screenshot = models.ImageField(upload_to='Project Images')
    bio = models.TextField()
    url =  models.CharField(max_length=250)
    link = models.CharField(max_length=250, null=True)
    slug = models.SlugField()
    date_created = models.DateTimeField(default=timezone.now())
    web_host_type = models.CharField(max_length=250, choices=WEB_HOST_TYPE, default='Cloud')
    web_host_provider = models.CharField(max_length=250, null=True)

    def get_absolute_url(self):
        return reverse('portfolio_app:projects', kwargs={'slug':self.slug})

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.name}')
        return super().save(*args, **kwargs)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    text = models.TextField()
    sender = models.EmailField()
    message_date = models.DateTimeField(default=timezone.now())


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index')

portfolio_app/forms.py
from django import forms
from portfolio_app import models


    
class ContactForm(forms.Form):
    name = forms.CharField(max_length=250)
    subject = forms.CharField(max_length=250)
    text = forms.CharField(max_length=2000, label='Description',
     help_text='Please fill in as much information as possible regarding any possible project collaborations or hire you have for me.',
     widget=forms.Textarea)
    sender = forms.EmailField(help_text='Please input your email address')



class ProjectForm(forms.ModelForm):
    name = forms.CharField(max_length=250, help_text='Enter latest project name', label='Project Name')
    link = forms.CharField(max_length=250, help_text='My github link serves as a major portfolio showing alot of my past and current works.', label='Github link')
    class Meta:
        model = models.Project
        fields = ['name', 'screenshot', 'link', 'bio', 'url', 'web_host_type', 'web_host_provider']

portfolio_app/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.core.mail import send_mail
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView
from portfolio_app import models
from django.contrib import messages


def contact(request):
    if request.POST == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            sender = form.cleaned_data['Sender']
            subject = form.cleaned_data['Subject']
            text = form.cleaned_data['Text']
            recipients = "mofeodujirin@gmail.com"
            send_mail(subject, text, sender, recipients)
            messages.success(request, 'Mail Sent successfully')

            return reverse('portfolio_app:contact')
    else:
        form = ContactForm()

    return render(request, "portfolio_app/contact.html", {"form":form})

def projects(request):
    return render(request, "portfolio_app/projects.html")

class ProjectListView(ListView):
    ordering = '-date_created'
    model = models.Project
    template_name = 'portfolio_app/index.html'

class ProjectDetailView(DetailView):
    model = models.Project
    template_name = 'portfolio_app/projects.html'


class ProjectCreateView(CreateView):
    model = models.Project
    template_name = 'portfolio_app/new_project.html'
    fields = ['name', 'screenshot', 'bio', 'url', 'link', 'web_host_type', 'web_host_provider']


class ProjectUpdateView(UpdateView):
    model = models.Project
    template_name = 'portfolio_app/update_projects.html'
    fields = ['name', 'screenshot', 'bio', 'url', 'link']

portfolio_app/templates/portfolio_app/contact.html
{% extends 'portfolio_app/index.html' %}
{% load crispy_forms_tags %}
{% load static %}


{%block content%}
<section>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
  {% if form.is_valid %}
  <p class="alert alert-success">{{success_img}}</p>
  {% endif %}
  <div class="container p-3">
 <form action="" method="POST">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" value="Send Message">
 </form>

  </div>
</section>
{%endblock%}

portfolio_app/templates/portfolio_app/index.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  <title>Welcome to my personal portfolio</title>
  {% endblock %}


  <script src="https://kit.fontawesome.com/c7c0aedab8.js" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js"></script>

  <link rel="stylesheet" href="{% static 'bootstrap-5/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.min.css' %}">

</head>
<body>
  {%  block content %}
  <section id="sec" class="container-fluid">
    <div class="row" >
      <div id="s1" class="col-sm-6 container-fluid bg-light">
        <p style="font-size: 25px; font-weight:bold;">MO</p>
        <div class="text-center " id="div-s1">
          <br><br><br><br><br><br><br>
          <p class="text-center" id="text-1">welcome to my</p>
          <a href="" class=""><i style="font-size: 50px;" class="fas text-warning fa-smile"></i></a>
        </div>
      </div>
      <div id="s2" class="col-sm-6 container-fluid bg-dark text-light">
        <p style="font-size: 20px; text-decoration: none; color: white; font-weight:bold;"><a href="#projects" style="border-radius: 50px; font-size: 14px;" class="btn btn-outline-light">recent projects </a> </p>
        <div class="text-center" id="div-s2">
          <br><br><br><br><br><br><br>
          <p class=" text-center" style="transition: 2s;" id="text-2">PORTFOLIO</p>
          <a href="#bio" class="bg-danger text-center" style="border-radius: 50px; padding: 10px; border: 0; color: white;"><i class="fas fa-angle-down"></i></a>
        </div>
      </div>

    </div>

  </section>


  <section class="p-4 bg-dark">
    <div class="about-me container text-center p-3">
      <h4 class="text-light" style="font-size: 16px; text-decoration: underline;">ABOUT ME</h4> <hr>
      <p class="text-light" style="font-size: 16px;">My name is <span style="font-weight: bold;" class="text-danger">Enimofe Odujirin</span> <br>
        <small class="text-light" style="font-size: 14px;">i'm a fullstack web developer based in Lagos, Nigeria.
          I have about four (4) years experience in Python, product design and development.</small>
        <br><br>
        <a href="" class="btn btn-danger p-2" style="border-radius: 0;" id="learn-more">Hire me</a>
      </p>
    </div>
  </section>


  <section class="p-3">
    <div id="bio" style="" class="container text-center p-5">
      <i class="text-success fas  fa-tv"></i><br>
      <b style="font-weight: bold;">WHAT I DO </b><br>
      <p style="font-size: 20px; padding: 5px;" class="lead">Its pretty simple i create
      web applications for my clients (<span class="text-danger" style="font-size: 10px; font-weight:bold;">Simple and Robust</span>).
        With Proper knowledge of both frontend and
        backend technologies i am able to
        turn my clients ideas into reality!</p>
    </div>


  </section>
  <div  class="container-fluid bg-light p-3 text-center ">
    <i class="fas fa-database text-danger"></i><br>
    <b style="font-weight: bold;">WHAT ELSE DO I DO</b>
 
    <p style="padding: px; " class="text-dark">
      I design proffesional, bright and sleek UI/UX screens for my clients.
    </p>
  </div>

  <div style="" class="container-fluid text-light bg-dark  p-3 text-center"><br>

    <p style="font-size: 13px;" class="lead">"Talented Junior Software Engineer adept at working with customers,
      team members and project leaders to accomplish software engineering and updating
      tasks according to timelines. Skilled working with wide range
       of front and back-end technologies to produce and evaluate code."</p><br>
  </div>
      <div style="" class="text-center p-3 text-dark">MY SERVICES</b><div><br>
  <div class="row" style="">

    <div class="col-lg-4 container-fluid text-light bg-dark text-center" style="padding: 100px;">

      <i  class="far fa-window-restore text-danger"></i>
     <h6 class="text-danger">DESIGN + DEVELOPMENT</h6>
     <p class='lead' style='font-size:16px;'>Clean modern designs, optimised for performance,
       search engines and converting users to customers.</p>
    </div>
    <div style="padding: 100px;" class="col-lg-4  text-center container-fluid bg-light text-dark">
      <i class="fas fa-mobile text-danger"></i>
      <h6 class="text-danger">MOBILE FRIENDLY</h6>
      <p class='lead' style='font-size:16px;'>A responsive design makes your website
         accessible to all users,
        regardless of their device.</p>
    </div>
    <div style="padding: 100px;" class="col-lg-4 bg-dark  container-fluid text-center text-light">

       <i class="fas fa-cart-plus text-danger"></i>
       <h6 class="text-danger">ECOMMERCE</h6>
       <p class='lead' style='font-size:16px;'>Integration of ecommerce platforms,
         payment gateways,
          custom product templates and more.</p>
    </div>
  </div>

  <section class="p-3">
 <div class="text-center" id="projects">
   <i class="fas fa-tasks text-center text-danger"></i>
  <p class="lead text-center">My Projects </p>
  <small class="text-center"><a href="#resume" class='text-danger' style="transition: 2s; text-decoration:none;">You can also check out my CV/Resume</a> </small>
 </div><br>
{% for project in project_list %}
<div class="container" >

  <div class="card" style='border-radius:0; box-shadow:4px;'>
    <div class="card-head bg-dark p-2 text-center">
      <p><a class='text-light' href="{{project.get_absolute_url}}">{{project.name}}</a></p>
    </div>
    <div class="card-body">
      <img src="{{project.screenshot.url}}" style="height: 96px;" class="img-fluid" alt="An Error Occured, cant display image" srcset="">
    </div>
    <div class="card-footer text-center">
      <p><i class="fas fa-link"></i> <a href="{{project.url}}">{{project.url}}</a></p>
    </div>
  </div>

</div><br>
{% endfor %}


  </section>

  <section>
    <div class="text-center container">
      <p>Would you like to contact me for hire?</p>
      <a href="{% url 'portfolio_app:contact' %}" style="border-radius: 0;" class="btn btn-dark">YES</a>
    </div><br>
  </section>
  <section id="resume" class="bg-danger container-fluid p-5">
    <div class="text-center">
      <h4 class="text-center text-light">MY RESUME</h4>
      <p class="text-center text-light"></p> <span><a href="https://www.github.com/mofhizziey"><i class="fa fas-github"></i></a></span>
      <p class="text-center text-light"></p> <span><a href="https://www.hackerrank.com/mofhizziey"><i class="fa fas-github"></i></a></span>
      <p class="text-center text-light" style="font-size: 14px;">Would you like to view my resume or download? you might really be interested in my works. Click the button!</p>
      <a href="{% static 'my_resume.pdf' %}" download="" class="text-center btn btn-outline-light btn-block" style="border-radius: 0;">Download Resume</a>
    </div>
  </section>

<section class="p-5">
  <footer class="text-center">

    <small style="font-size:12px;" class="text-center">Click any of the links below if you would like to contact me for gigs, collabs and so on.</small> <hr>
    <a href="https://www.github.com/mofhizziey"><i style ='font-size:65px;'  class="fab fa-github text-center text-dark" ></i></a>
    <a href="https://www.twitter.com/blaxcxx"><i style ='font-size:65px;'  class="pl-3 fab fa-twitter text-center text-info" ></i></a>
    <a href="https://wa.me/+2349136082942"><i style ='font-size:65px;'  class="pl-3 fab fa-whatsapp text-success text-center" ></i></a>
  </footer>
</section>

  {% endblock %}
</body>




<script>

  gsap.from('#sec', {opacity:0, duration: 1, y:-50})


</script>



<script src="{% static 'js/jquery-3.5.0.js' %}"></script>
<script src="{% static 'bootstrap-5/js/bootstrap.min.css' %}"></script>
</html>

portfolio_app/templates/portfolio_app/new_project.html
{% extends 'portfolio_app/index.html' %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Add a new project</title>
  {% endblock %}
{% block content %}
<section class="p-3">
    <div class="container p-2 offset">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form |crispy}} <hr>
            <input type="submit" class="btn btn-success btn-block btn-lg" value="Create New Project" name="" id="">
        </form>
      </div>
</section>
{% endblock %}

portfolio_app/templates/portfolio_app/projects.html
{% extends 'portfolio_app/index.html' %}
{% block title %}
  <title>{{project.name}} Detail</title>
  {% endblock %}

{% block content %}
<section class="">
    <div class="container p-3 text-center">
        <div class="card p-2">
            <div class="card-head">
                <h3>{{project.name}}</h3>
                <small class="text-muted">{{project.date_created}}</small>
            </div>
            <div class="card-img-top">
                <img src="{{project.screenshot.url}}" class="img-fluid" alt="An Error Occured, cant display image" srcset="">
            </div>
          <div class="card-body">  
            <div class="container">
                <h4 class="text-center">About the project</h4>
                <p class="lead" style="font-size: 14px;">
                    {{project.bio}}
                    
                </p><hr>
                <div class="container">
                    <h4 class="text-center">Type of web host</h4>
                    <p class="lead" style="font-size: 14px;">
                        <a href="">{{project.web_host_type}}</a>
                    </p>
                </div>
            </div>
          </div>
          <div class="container">
            <h4 class="text-center">Web host provider</h4>
            <p class="lead" style="font-size: 14px;">
                <a href="">{{project.web_host_provider}}</a>
            </p>
        </div>
          <div class="container">
            <h4 class="text-center">Github Link</h4>
            <p class="lead" style="font-size: 14px;">
                <a href="{{project.link}}">{{project.link}}</a>
            </p>
        </div>
      </div>
          <div class="card-footer text-center">
            <p><i class="fas fa-link"></i> {{project.url}}</p>
          </div>
        </div>
      </div><br>

     
</section>
{% endblock %}

portfolio_app/templates/portfolio_app/update_projects.html
{% extends 'portfolio_app/index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  <title>Update current project</title>
  {% endblock %}
{% block content %}
<section>
    <div class="container p-3 ">
        <form action="" method="post">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-success" value="Update Project">
        </form>
    </div>
</section>

{% endblock %}